// web/src/app/modules/index/index.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  templateUrl: './index.component.html',
  styleUrls: ['./index.component.scss'],
})
export class IndexComponent implements OnInit {
  introImg: string = 'assets/images/intro-img.jpg';

  constructor() {
    document.title = 'Pagina Inicial - Minha Aula';
  }

  ngOnInit(): void {}
}

<main class="intro" title="Introdução">
  <div class="intro--container">
    <app-header [secondaryLogo]="true"></app-header>
    <div class="container">
      <div class="row intro__content">
        <div class="col-12 col-sm-7">
          <h1 class="intro__title">SUA PLATAFORMA DE AGENDAMENTO DE AULAS</h1>
          <p class="intro__tagline">
            Marque com um professor, ou aluno, e assista ou lecione aulas de
            onde estiver
          </p>
          <div class="button-group">
            <app-button
              path="user/login"
              content="Assista as aulas"
            ></app-button>
            <app-button
              path="user/login"
              content="Dê aulas"
              [colors]="{ background: '#cfc123', color: '#322c2c' }"
            ></app-button>
          </div>
        </div>
        <div class="col-12 col-sm-5">
          <img [src]="introImg" alt="Imagem da introdução" class="intro__img" />
        </div>
      </div>
    </div>
  </div>
</main>

// src/pages/Index/index.tsx
import React from "react";
// components
import { Grid, Container } from "@material-ui/core";
import Header from "../../components/Header/index";
// styled-components
import { IntroContainer } from "./styles";
import { Button } from "../../styles/objects/button";
// imgs
import introImg from "../../assets/intro-img.jpg";
import logoImg from "../../assets/logo.svg";

const Index = () => {
  return (
    <>
      <IntroContainer>
        <Header logo={logoImg} />
        <Container>
          <Grid
            container
            spacing={2}
            alignItems="center"
            style={{ marginTop: "var(--gap-lg)" }}
          >
            <Grid item container xs={12} sm={7}>
              <h1>SUA PLATAFORMA DE AGENDAMENTO DE AULAS</h1>
              <p>
                Marque com um professor, ou aluno, e assista ou lecione aulas de
                onde estiver
              </p>
              <div>
                <Button to="/aluno/login">Assista aulas</Button>
                <Button
                  background="var(--secondary-2)"
                  color="var(--support-4)"
                  to="/professor/login"
                >
                  Dê aulas
                </Button>
              </div>
            </Grid>
            <Grid item container xs={12} sm={5}>
              <img src={introImg} alt="Imagen da introdução" />
            </Grid>
          </Grid>
        </Container>
      </IntroContainer>
    </>
  );
};

export default Index;
